name: matrix-on-push
on:
  # run on push
  push:
    branches:
      - '**'

jobs:
  gen-matrix:
    timeout-minutes: 10
    name: gen matrix
    # do not run this job if skip ci is in commit message
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    outputs:
      tasks: ${{ steps.get-matrix.outputs.TASKS }}

    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          # get lfs items
          lfs: true
          # fetch all commits, slower but required to pass to nx
          fetch-depth: 0

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16.10.0'
          cache: 'npm'

      - name: cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts

      - name: install global nx
        run: npm install -g @nrwl/cli

      - name: set outputs
        id: get-matrix
        run: |
          echo "::set-output name=TASKS::$(node ./tools/nrwl-utils/gen-matrix.js $GITHUB_REF)"

  print-matrix:
    runs-on: ubuntu-latest
    needs: [gen-matrix]
    steps:
      - name: print matrix
        run: echo "${{ fromJson(steps.gen-matrix.outputs.TASKS) }}"

  # TODO: Add job matrix generations
