name: on-push
on:
  # run on push
  push:
    branches:
      - '**'

jobs:
  core-pipeline:
    timeout-minutes: 10
    name: core pipeline
    # do not run this job if skip ci is in commit message
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          # get lfs items
          lfs: true
          # fetch all commits, slower but required to pass to nx
          fetch-depth: 0

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16.10.0'
          cache: 'npm'

      - name: cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts

      - name: install global nx
        run: npm install -g @nrwl/cli

      - name: nx:report
        run: nx report

      - name: nx:workspace-lint
        run: nx workspace-lint

      - name: run-many
        run: node ./tools/nrwl-utils/run-many.js ${{ matrix.target }} ${{ matrix.jobIndex }} ${{ env.jobCount }} $GITHUB_REF
# TODO: add environment support for `test` `stage` and `prod`
# TODO: see docs for adding specific deployment pipelines

